print("hello,world!")
print(5+3)
print("Python","is","fun!")
print("she said,\"hello!\"")
print("first line\nsecond line")
print("item 1\tltem 2 \tltem 3")
print("the result is ",42)
print(12345)
print(3.14159)
print("dollar sign:$")
print("apple","banana","cherry", sep= ",")
print("hello,",end="")
print("world!")
print("Python! "* 3)
print("\u2764")#prints a heart symbol
print()
print("hello" +"world!")
print(1.2e3) # Prints 1200.0
print("true")
print("false")
print("""this is a multiline print statement""")
print("this is a backslash:\\")